//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_FINAL_PROG_II_20187053.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
    {

        public int Id { get; set; }
        [Required(ErrorMessage = "El Cedula no puede estar vacío")]
        [MinLength(length: 13)]
        [MaxLength(length: 13)]
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail no tiene el formato correcto" +
        "\nEjemplo: Pedro00@gmail.com")]
        public string Email { get; set; }
     
        public string Departamento { get; set; }
        [Required(ErrorMessage = "El Cargo no puede estar vacío")]
        [MinLength(length: 5)]
        [MaxLength(length: 50)]
        public string Cargo { get; set; }
        public string Fecha { get; set; }
        public int Salario { get; set; }
    }
}
