//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_FINAL_PROG_II_20187053.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINAS
    {
        public int Id { get; set; }
        public int Mes { get; set; }
        public int Año { get; set; }
        public int Monto { get; set; }
    }
}
